### ISSUE TITLE
Jolla C and qcrypto

### ISSUE THREAD

**Issue by fuchsmich** [Olf0/crypto-sdcard#86]
As requested in the [README](https://github.com/Olf0/crypto-sdcard/blob/qcrypto/README.md):

    $ find /lib/modules/ -name qcrypto.ko

returns nothing.

**Comment by Olf0** [comment]
Thank you!

The thing is, I expected a positive result from looking at a l500d kernel tree for SailfishOS somewhere here at Github.
Can you please provide the output of `ssu s` (as a user) sans device UID.

Maybe the access rights for the kernel module directories were tightened, hence can you please retry the `find /lib/modules/ -name qcrypto.ko` as root.
If positive, then it is also helpful to know if a `/sbin/modprobe qcrypto` succeeds (in addition to the already mentioned output of `rpm -qf $(find /lib/modules/ -name qcrypto.ko)`.

**Comment by Olf0** [comment]
Or (desperate) does `devel-su find -name "*crypto*"` yield something?

**Comment by Olf0** [comment]
Or (even more desperate) a `devel-su find / -name "*crypto*.ko"`?

**Comment by fuchsmich** [comment]
```
[root@jollac nemo]# find / -name "*crypt*.ko"
find: /sys/kernel/slab/L2TP/IPv6: No such file or directory
find: /sys/kernel/slab/L2TP/IP: No such file or directory
/lib/modules/3.10.49+0.0.95/ecryptfs.ko
```

**Comment by Olf0** [comment]
Thank you, so the Jolla C must use the "regular edition" of crypto-sdcard.

Now I assume again, that only on the Jolla 1 SailfishOS provides the `qcrypto.ko`.

Background: Qualcomm's "Crypto Engine" (basically a cryptographic accelerator) was introduced to their ARMv7-A based SoCs (regardless of the specific CPU core used).  The SoC in the J1 has v2 of that engine, the one in the l500d has v3.
This is why I assumed that the low-level software mechanisms are the same (and AFAICS they are under Android).
